# Generated by Django 5.2.1 on 2025-06-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complemento',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='piernas',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='tronco',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='zapatos',
            name='nombre',
        ),
        migrations.AddField(
            model_name='complemento',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='piernas',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tronco',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zapatos',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
