# Generated by Django 5.2.1 on 2025-06-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='complemento',
            name='color',
            field=models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3),
        ),
        migrations.AddField(
            model_name='complemento',
            name='genero',
            field=models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='piernas',
            name='color',
            field=models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3),
        ),
        migrations.AddField(
            model_name='piernas',
            name='genero',
            field=models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='piernas',
            name='subcategoria',
            field=models.CharField(choices=[('JEA', 'Jeans'), ('BUS', 'Buso'), ('SHT', 'Short'), ('FAL', 'Falda'), ('VES', 'Vestidos')], default='JEA', max_length=3),
        ),
        migrations.AddField(
            model_name='tronco',
            name='color',
            field=models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3),
        ),
        migrations.AddField(
            model_name='tronco',
            name='genero',
            field=models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='tronco',
            name='subcategoria',
            field=models.CharField(choices=[('POL', 'Poleras'), ('PLN', 'Poleron'), ('CAM', 'Camisas')], default='POL', max_length=3),
        ),
        migrations.AddField(
            model_name='zapatos',
            name='color',
            field=models.CharField(choices=[('NEG', 'Negro'), ('BLN', 'Blanco'), ('GRS', 'Gris'), ('AZM', 'Azul marino'), ('BEI', 'Beige'), ('ROJ', 'Rojo'), ('VDO', 'Verde oliva'), ('MAR', 'Marrón'), ('AZC', 'Azul claro'), ('ROS', 'Rosado')], default='NEG', max_length=3),
        ),
        migrations.AddField(
            model_name='zapatos',
            name='genero',
            field=models.CharField(choices=[('HOM', 'Hombre'), ('MUJ', 'Mujer'), ('UNI', 'Unisex')], default='UNI', max_length=3),
        ),
        migrations.AddField(
            model_name='zapatos',
            name='subcategoria',
            field=models.CharField(choices=[('ZAP', 'Zapatillas'), ('BOT', 'Botos'), ('SAN', 'Sandalias'), ('MOC', 'Mocasines'), ('PAN', 'Pantuflas')], default='ZAP', max_length=3),
        ),
    ]
