# Generated by Django 5.2.3 on 2025-06-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_complemento_color_complemento_genero_piernas_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajaConNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('puesto', models.CharField(choices=[('VEN', 'Vendedor'), ('LID', 'Líder de Equipo')], max_length=3)),
                ('mensaje', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
    ]
