# Generated by Django 5.2.3 on 2025-06-28 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_sesocio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('RM', 'Región Metropolitana de Santiago'), ('I', 'Región de Tarapacá'), ('II', 'Región de Antofagasta'), ('III', 'Región de Atacama'), ('IV', 'Región de Coquimbo'), ('V', 'Región de Valparaíso'), ('VI', 'Región de O’Higgins'), ('VII', 'Región del Maule'), ('VIII', 'Región del Biobío'), ('IX', 'Región de La Araucanía'), ('XIV', 'Región de Los Ríos'), ('X', 'Región de Los Lagos'), ('XI', 'Región de Aysén'), ('XII', 'Región de Magallanes'), ('XV', 'Región de Arica y Parinacota'), ('XVI', 'Región de Ñuble')], max_length=4)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('monto_carrito', models.IntegerField()),
                ('costo_envio', models.IntegerField()),
                ('total_pagar', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
